version: '2'
services:
  jhcrawl-app:
    image: jhcrawl
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhcrawl-mysql:3306/jhcrawl?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhcrawl-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhcrawl-elasticsearch:9200
    ports:
      - 8080:8080
  jhcrawl-mysql:
    extends:
      file: mysql.yml
      service: jhcrawl-mysql
  jhcrawl-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhcrawl-elasticsearch
